// Tiny manifest of templates that have a step-by-step explanation registered.
// Imported synchronously by CodePlayground to decide whether to render the
// "Explain" button without pulling in the full explanation bodies.
// Kept in lockstep with the keys of `playgroundExplanations` in
// ./playgroundExplanations.ts.

export const playgroundExplanationKeys: ReadonlySet<string> = new Set([
  // ===== Coding Challenges (69) =====
  'Two Sum',
  'Reverse String',
  'Valid Palindrome',
  'FizzBuzz',
  'Max Profit',
  'Valid Parentheses',
  'Merge Sorted Arrays',
  'Flatten Array',
  'Debounce',
  'Group Anagrams',
  'Find Duplicates',
  'Remove Duplicates',
  'Find Missing Number',
  'Move Zeros',
  'Rotate Array',
  'Bubble Sort',
  'Quick Sort',
  'Merge Sort',
  'Anagram Check',
  'Longest Substring',
  'First Non-Repeating Char',
  'Sum Curry',
  'Memoize',
  'Deep Clone',
  'Throttle',
  'EventEmitter',
  'LRU Cache',
  'Compose & Pipe',
  'Binary Search',
  'Roman to Integer',
  'Reverse Linked List',
  'Container With Most Water',
  'Climbing Stairs',
  'Balanced Brackets (Count)',
  'Second Largest Number',
  'Maximum Subarray',
  'Trapping Rain Water',
  '3Sum',
  'Generate Parentheses',
  'Subsets',
  'Permutations',
  'Min Stack',
  'Daily Temperatures',
  'Coin Change',
  'House Robber',
  'Jump Game',
  'Detect Cycle in Linked List',
  'Merge Two Sorted Lists',
  'Sort Colors',
  'Top K Frequent Elements',
  'Subarray Sum Equals K',
  'Single Number',
  'Single Number II',
  'Majority Element',
  'Product of Array Except Self',
  'Plus One',
  'Longest Common Prefix',
  'Longest Palindromic Substring',
  'Reverse Vowels of a String',
  'String to Integer (atoi)',
  'Letter Combinations of Phone Number',
  'Reverse Words in a String',
  'Rotate Array Left',
  'Spiral Matrix',
  'Search in Rotated Sorted Array',
  'Find Maximum in Array',
  'Find Min and Max',
  'Third Largest Number',
  'Kth Largest Element',
  'Find Peak Element',
  // ===== JS Fundamentals (6) =====
  'Hello World',
  'Array Methods',
  'Closures',
  'Promises & Async',
  'Map & Set',
  'Spread & Rest',
  // ===== JS Interview Topics (7) =====
  'Event Loop & Microtasks',
  'this Keyword',
  'Debounce & Throttle',
  'Currying',
  'Prototypes & Classes',
  'Destructuring Deep Dive',
  'Tricky Interview Q',
  // ===== React (6) =====
  'useState Counter',
  'useEffect Lifecycle',
  'Custom Hook',
  'useReducer Todo',
  'Context API',
  'React Compiler Patterns',
  // ===== JS Polyfills (31) =====
  'Array.map',
  'Array.filter',
  'Array.reduce',
  'Array.forEach',
  'Array.find & findIndex',
  'Array.some & every',
  'Array.flat & flatMap',
  'Function.bind',
  'Function.call & apply',
  'Promise.all',
  'Promise.allSettled',
  'Promise.race & any',
  'Array.includes',
  'Object.assign',
  'Array.from',
  'Array.sort',
  'Array.indexOf / lastIndexOf',
  'Array.reverse',
  'Array.slice',
  'Array.splice',
  'Array.concat',
  'String.padStart / padEnd',
  'JSON.stringify',
  'Object.keys / values / entries',
  'JSON.parse',
  'Array.isArray',
  'Object.create',
  'Object.freeze + deepFreeze',
  'Array.prototype.fill',
  'String.prototype.repeat',
  'Array.prototype.join',
]);
